
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  publishVstsFeed: 'OVERRIDE THIS'
  group: ${{variables['Build.DefinitionName']}}
steps:

- task: UseDotNet@2
  displayName: Install .NET 6.0
  inputs:
    packageType: 'sdk'
    version: '6.0.x'

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  displayName: 'Restore Library Dependencies'
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: 'Build Library'
  inputs:
    command: 'build'
    projects: './MongoDbGenericRepository/MongoDbGenericRepository.csproj'
    arguments: '--configuration $(buildConfiguration)'

# - task: DotNetCoreCLI@2
#   displayName: 'Test Library'
#   inputs:
#     command: 'test'
#     projects: './test/AspNetCore.Identity.MongoDbCore.IntegrationTests/AspNetCore.Identity.MongoDbCore.IntegrationTests.csproj'
#     arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Package Library (nuget)'
  inputs:
    command: 'custom'
    projects: './MongoDbGenericRepository/MongoDbGenericRepository.csproj'
    custom: 'pack'
    arguments: '--no-build -o $(build.artifactStagingDirectory)/Nuget'
    verbosityPack: 'Detailed'

- task: NuGetCommand@2
  displayName: 'Publish Library'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '$(publishVstsFeed)'
    verbosityPush: 'Normal'